### ISSUE TITLE
flatten_timepoint_specific_output_overrides fails

### ISSUE THREAD

**Issue by LeonardSchmiester** [PEtab-dev/PEtab#363]
I'm getting the following error when using the function: 
```
Traceback (most recent call last):
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 4525

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/petab/core.py", line 140, in flatten_timepoint_specific_output_overrides
    df_unique_values.loc[nrow, OBSERVABLE_ID])
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexing.py", line 1761, in __getitem__
    return self._getitem_tuple(key)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexing.py", line 1271, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexing.py", line 1388, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexing.py", line 1964, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexing.py", line 624, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/generic.py", line 3537, in xs
    loc = self.index.get_loc(key)
  File "/home/leonard/Anaconda/envs/general/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 4525
```

The problem seems to be, that some indices are missing after `df_unique_values = df.drop_duplicates()`.
Changing line 137 from `for nrow in range(len(df_unique_values.index)):` to `for nrow in df_unique_values.index:` should fix this problem.

Still, I get an empty measurement df, when preequilibration conditions are NaN, because of lines 141-142 (`petab_problem.measurement_df[PREEQUILIBRATION_CONDITION_ID] <= df_unique_values.loc[nrow, PREEQUILIBRATION_CONDITION_ID]`) .

**Comment by LeonardSchmiester** [comment]
Additionally it fails with `TypeError: expected a string object, not float`, when we have measured noiseParameters

**Comment by yannikschaelte** [comment]
@LeonardSchmiester to which problem are you applying the function?

**Comment by LeonardSchmiester** [comment]
I used it for CanPathPro. But should also apply for e.g. Isensee I think.

**Comment by LeonardSchmiester** [comment]
This can be closed, right @yannikschaelte ?

**Comment by yannikschaelte** [comment]
When it's on master, yes

**Comment by yannikschaelte** [comment]
done in #423
