### ISSUE TITLE
Visualization: plotTypeData ' replicate ' not working

### ISSUE THREAD

**Issue by erikadudki** [PEtab-dev/PEtab#503]
**Which problem would you like to address? Please describe.**
I try to plot individual replicates of the data.  
1. If I have the column `plotTypeData` with `replicate` in the visualization table, the data is still plotted as `MeanAndSTD`. You manually have to add `plotted_noise='replicate'` in: 
```
plot_data_and_simulation(data_file_path,
condition_file_path,
visualization_file_path,
simulation_file_path, plotted_noise='replicate'
)
```
2. Doing that, an error arises:
```
Traceback (most recent call last):
  File "/home/erika/Documents/Python/PEtab_my_files/Boehm_visu_test.py", line 21, in <module>
    simulation_file_path, plotted_noise='replicate'
  File "env-petabpypesto37/lib/python3.7/site-packages/petab/visualize/plot_data_and_simulation.py", line 165, in plot_data_and_simulation
    exp_conditions, sim_data)
  File "env-petabpypesto37/lib/python3.7/site-packages/petab/visualize/helper_functions.py", line 765, in handle_dataset_plot
    plot_lowlevel(plot_spec, ax, conditions, measurement_to_plot, plot_sim)
  File "env-petabpypesto37/lib/python3.7/site-packages/petab/visualize/plotting_config.py", line 93, in plot_lowlevel
    conditions[conditions.index.values],
AttributeError: 'numpy.ndarray' object has no attribute 'index'
```
so `conditions` seems to have the wrong data type, here its an numpy.array with the time-points, that should be plotted on the x-axis. 

**Describe the solution you would like**
1. It would be nice if only defining  `plotTypeData` with `replicate` in the visualization table would be enough (and not additionally adding `**plotted_noise='replicate'**` in the function `plot_data_and_simulation`. Could be easier to understand for beginners.
2. Despite of addressing the error, it would be nice, if also one datapoint could be plotted as replicate, such that I can plot one datapoint with the marker 'x' (For now I have to plot it with `MeanAndSTD` which uses the marker '.' which leads to invisible overlapping  between data points and simulation points ('o').
![Screenshot from 2021-02-03 19-37-54](https://user-images.githubusercontent.com/49193148/106796670-f72e5d00-665b-11eb-933c-11f628ab8673.png)

**Describe alternatives you have considered**
-

**Additional context**
-

**Comment by erikadudki** [comment]
same for `plotTypeData` = `provided`, it does not show the errorbars, because it automatically sets `plotTypeData` to `MeanAndSD`. To plot the errorbars the user needs to define: 
```
plot_data_and_simulation(data_file_path,
condition_file_path,
visualization_file_path,
simulation_file_path, 
plotted_noise='provided'
)

```
which should be automatically inferred from the visu-specification table, if available.
