### ISSUE TITLE
Logic of petab.visualize.helper_functions.get_vis_spec_dependent_columns_dict

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#504]
So I am currently running into the following issue:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "pretrain_per_sample.py", line 70, in <module>
    petab.visualize.plot_data_and_simulation(
  File "/Users/ffroehlich/Documents/HMS/mechanismEncoder/venv/lib/python3.8/site-packages/petab/visualize/plot_data_and_simulation.py", line 128, in plot_data_and_simulation
    exp_data, vis_spec = create_or_update_vis_spec(exp_data,
  File "/Users/ffroehlich/Documents/HMS/mechanismEncoder/venv/lib/python3.8/site-packages/petab/visualize/helper_functions.py", line 572, in create_or_update_vis_spec
    vis_spec = expand_vis_spec_settings(vis_spec, columns_dict)
  File "/Users/ffroehlich/Documents/HMS/mechanismEncoder/venv/lib/python3.8/site-packages/petab/visualize/helper_functions.py", line 487, in expand_vis_spec_settings
    vis_spec[select_conditions].loc[:, column].values[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I explicitly specify `PLOT_ID` but no `DATASET_ID` in my visualization table (if I do specify `DATASET_ID`, which is not specified in my measurements_df, petab will just show empty plots, ... bummer).

This means that I end up with `https://github.com/PEtab-dev/PEtab/blob/c3d51d6ce98a533c686243dd9ba163276785fc44/petab/visualize/helper_functions.py#L558`, which makes no effort at all to respect the previously defined `plot_id_list`, but instead creates a new set of plot ids of the form `plot{i}`. Those `PLOT_ID` of course don't match what's in my `vis_spec`, which means that the `select_conditions` in https://github.com/PEtab-dev/PEtab/blob/c3d51d6ce98a533c686243dd9ba163276785fc44/petab/visualize/helper_functions.py#L484 will never match anything.

I am at loss how this is conceptually supposed to work at all, so I would appreciate if anybody could enlighten me such that I can fix this issue.

**Comment by yannikschaelte** [comment]
@MerktSimon @erikadudki @plakrisenko I am unfortunately not familiar with these lines. Do you know how it's supposed to work?

**Comment by erikadudki** [comment]
So, I think if you want to use the visualization table without the datasetId, then it will infer the observables from the column `YValues` and will try to plot each observable in one subplot. And this should then coincide with the given plotIds (one plotId, one observable). But I suppose you are trying to plot multiple observables into one subplot, given the plotId? As far as I know, grouping by `plotId` is not yet implemented (and I guess is to discuss for which cases this could be implemented) . Please anyone, correct me if I'm wrong.
I think for special requests for plotting things `datasetId` should be the way to go, but you said, this also does not work for you...? Could you elaborate a bit on what you are trying to plot / group together?

**Comment by FFroehlich** [comment]
[dream_cytof__EGFR_MAPK_AKT_STAT__c184A1__visualization.txt](https://github.com/PEtab-dev/PEtab/files/5934172/dream_cytof__EGFR_MAPK_AKT_STAT__c184A1__visualization.txt)

I have attached one of the visualization tables I used. The data consists of a couple of dynamic observables that are measured in multiple conditions, where I would like individual plots for every obervables with line plots for every observable, as well as a couple of static observables that are only measured once in the baseline condition, where I would like a bar plot of all those observables in a single plot. I tried using `datasetId` for grouping, but I ran into issues since I am not using (and probably shouldn't since the grouping is different from what I want in the plots) `datasetId` in the measurement table.

**Comment by erikadudki** [comment]
Thank you for the visualization table! From what I can see in the table and your descriptions, I would say that should be doable with using `datasetIds`? May I ask, what is the reason, why you cannot use `datasetId` in the measurement table? What do you mean by "since the grouping is different from what I want in the plots" ? Generally, I thought it should be possible to group the plots as wanted with the datasetIds.

**Comment by FFroehlich** [comment]
> Thank you for the visualization table! From what I can see in the table and your descriptions, I would say that should be doable with using `datasetIds`? May I ask, what is the reason, why you cannot use `datasetId` in the measurement table? What do you mean by "since the grouping is different from what I want in the plots" ? Generally, I thought it should be possible to group the plots as wanted with the datasetIds.

I just read the documentation again and I it is possible. I was a little confused about the implications of setting that parameter but as it is supposed to only influence plotting, I guess it's all fine. Could be that just setting `datasetId` to `simulationConditionId` is a better default than whats currently implemented.
